### ISSUE TITLE
Build from your button, added token, and can't run

### ISSUE THREAD

**Issue by YuiyuD** [Macley-Kun/Discord-Selfbot#3]
# READ THIS
We are aware of the fact that the Discord server has been deleted. Please do not post additional issues talking about this. If your issue is not related to the deletion of the server, please delete this text and enter in your issue as normal.

## About the issue tracker
The GitHub issue tracker is for reporting problems in bot code only. We are unable to assist you in problems arising from user error or your own configuration issues.

and I got this, how to fix them, what was I mistaken, thank you
![image](https://user-images.githubusercontent.com/28624505/54081252-2931ca00-4334-11e9-801a-11513c0521b4.png)

**Comment by Macley-Kun** [comment]
Wait what? I’m not the developer I just forked it.
That error isn’t bad just means your using more memory then you should.
Bot will stay up, aslong as you don’t hit the 1024 mark.

I don’t give any support about this, and please don’t use my google API key, it’s mines and I can’t use an env variable for it and the dev isn’t responding to my messages.

PLEASE JUST FORK IT AND REMOVE THE GOOGLE API KEYS!!!!
